<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/23
 * Time: 20:52
 */

namespace app\admin\controller;


use app\BaseController;
use think\facade\Session;

class UserBase extends BaseController
{
	#登陆信息
	protected $userinfo;
	protected $site_id;
	protected $user_id;
	protected $access;
	protected $siteinfo;
	#面包屑导航
	protected $crumbs = '';

	public function initialize()
	{
		parent::initialize(); # TODO: Change the autogenerated stub
		$this->checkLogin();
		if (!$this->checkPower()) {
			if ($this->request->isPost() || $this->request->isAjax()) {
				exit($this->ajaxFail('没有权限'));
			} else {
				trigger_error('没有权限');
			}
		};
	}


	/**
	 * 检查用户是否登录
	 */
	private function checkLogin()
	{
		$login_info = Session::get('login_info');
		if ($login_info) {
			$this->userinfo = $login_info['admin_user']??[];
			$this->access = $login_info['admin_access']??[];
			$this->siteinfo = $login_info['site']??[];
			//$this->site_id = $this->userinfo['site_id']??'';
			$this->user_id = $this->userinfo['user_id']??'';
			return true;
		} else {
            return redirect('/admin/login');
			exit();
		}
	}


	/**
	 * 检查用户权限
	 * @param string $access
	 * @return bool
	 */
	protected function checkPower($access = '')
	{
		if (!is_product()) {
			return true;
		}
		if (!$access) {
			$access = strtolower($this->request->module() . '/' . $this->request->controller() . '/' . $this->request->action());
		} else {
			$access = trim(strtolower($access), '/');
		}
		#跳过共享权限
		$sharePower = array('admin/Index/index', 'admin/Rbac/ajaxCheckPower');
		foreach ($sharePower as $v) {
			if (strtolower($access) == strtolower($v)) {
				return true;
			}
		}
		#获取用户权限
		$url_arr = array();
		foreach ($this->access as $v) {
			$url_arr[] = strtolower(trim($v['url'], '/'));
		}
		if (in_array($access, $url_arr)) {
			return TRUE;
		} else {
			return FALSE;
		}
	}


	/**
	 * 面包屑导航
	 * @param $crumb
	 */
	private function crumb($crumbs = array())
	{
		$crumbsHtml = '';
		if (!empty($crumbs)) {
			$crumbsHtml .= '<li><a href="' . url('admin/Index/index') . '"><i class="fa fa-home"></i> 首页</a></li>';
			$n = 0;
			foreach ($crumbs as $key => $value) {
				$n++;
				$link_s = !empty($value) ? '<a href="' . $value . '">' : '';
				$link_e = !empty($value) ? '</a>' : '';
				if ($n == count($crumbs)) {
					$crumbsHtml .= '<li class="active color4">' . $key . '</li>';
				} else {
					$crumbsHtml .= '<li>' . $link_s . $key . $link_e . '</li>';
				}
			}
		}
		$this->assign('crumbs', $crumbsHtml);
		return $crumbsHtml;
	}

	private function leftMenu()
	{
		#左侧菜单
		$list = [];
		foreach ($this->access as $v) {
			if (!in_array($v['level'], [1, 2])) {
				continue;
			}
			$v['url'] = url($v['url']);
			$list[] = $v;
		}
		$this->assign('left_menu', treeStructForLayer($list));
	}


	protected function myFetch($template = '', $vars = [], $config = [])
	{
		$template = 'layuimini' . DIRECTORY_SEPARATOR . $template;
		#站点信息
		$this->assign('site_info', $this->getSiteInfo());
		#登录信息
		$this->assign('login_info', $this->userinfo);
		return parent::fetch($template, $vars, $config); // TODO: Change the autogenerated stub
	}

	protected function getSiteInfo($key = '')
	{
		if ($key && isset($this->siteinfo[$key])) {
			return $this->siteinfo[$key];
		} else {
			return $this->siteinfo;
		}
	}

	protected function apiRequest($url, array $param = [], $method = self::method_get)
	{
		$param['_user_id'] = $this->user_id;
		$param['_site_id'] = $this->site_id;
		return parent::apiRequest($url, $param, $method); // TODO: Change the autogenerated stub
	}


}