<?php
/**
 * Created by PhpStorm.
 * User: mgckid
 * Date: 2022/1/15
 * Time: 19:25
 */

namespace app\appdal\controller;


use app\BaseController;
use app\middleware\AppAuth;

class Base extends BaseController {

    protected $middleware = [AppAuth::class];
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}